import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import './globals.css'

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-jost',
})

export const metadata: Metadata = {
  title: 'Live Trivia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth! overflow-x-hidden"
    >
      <body
        className={`${jost.className} text-gray-50 bg-gray-950 tracking-wide max-w-[100vw] overflow-x-hidden flex flex-col min-h-screen`}
      >
        <main className="flex flex-col items-center gap-36 px-4 justify-center py-12">
          {children}
        </main>
      </body>
    </html>
  )
}
